BLACK = (0, 0, 0)                                               # black
WHITE = (255, 255, 255)                                         # white
RED = (255, 0, 0)                                               # red
GREY = (140, 140, 140)                                          # grey
GREEN = (0, 255, 0)                                             # green
BACKGROUND_COLOR = (189, 189, 189)                              # grey for grid_spacing and sector_spacing
SUB_BACKGROUND_COLOR = (113, 113, 113)                          # darker grey for menu backdrops
LIGHT_RED = (250, 87, 87)                                       # light red for wrong cells
LIGHT_GREY = (207, 204, 204)                                    # light grey for marked cells
